// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
const spec_Identifier = {__proto__:null,and:40, or:42}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOOOQO'#C_'#C_O_QPO'#C_OdQPO'#C^QOQPOOOOQO,58y,58yOiQPO,58xOwQPO'#C_OOQO'#Cg'#CgOOQO'#Ch'#ChO!PQPO'#CfOOQO'#Co'#CoO!UQPO'#CnO!^QPO1G.dO!cQPO,58|O!kQPO,59QOiQPO'#CiO!pQPO,59YOOQO7+$O7+$OOOQO1G.h1G.hOiQPO1G.lOOQO,59T,59TOOQO-E6g-E6gO!xQPO7+$WOOQO<<Gr<<Gr",
  stateData: "!}~O`OS~OSQOTPO~OTTO~OaUO~OSQOTVOdWOeXO~OV^OaRX~Of_O~Oh`OgbX~OgbO~OWcOXcO~OadO~Oh`Ogba~OghO~O",
  goto: "!]dPPemPPhPPPhssxPPPP!O!UQSOVZU`dXROU`dVYU`dQa[RfaQ]URgdS[UdRe`",
  nodeNames: "⚠ Program QueryRule LSide Negation Identifier SimpleRule Operator Number String GroupRule And Or",
  maxTerm: 24,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "%S~RgX^!jpq!jrs#_|}#|!Q![$R![!]$Z!^!_$`!_!`$`!`!a$`!c!}$e#R#S$e#T#o$e#o#p$s#q#r$x#r#s$}#y#z!j$f$g!j#BY#BZ!j$IS$I_!j$I|$JO!j$JT$JU!j$KV$KW!j&FU&FV!j~!oY`~X^!jpq!j#y#z!j$f$g!j#BY#BZ!j$IS$I_!j$I|$JO!j$JT$JU!j$KV$KW!j&FU&FV!j~#bTOr#_rs#qs;'S#_;'S;=`#v<%lO#_~#vOX~~#yP;=`<%l#_~$ROh~~$WPW~!Q![$R~$`Of~~$eOV~~$jRT~!c!}$e#R#S$e#T#o$e~$xOa~~$}Og~~%SOS~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 5, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
