// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
const spec_Name = {__proto__:null,and:68, or:70}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'tOVQPOOO_QPO'#CaOmQPO'#CaOrQPO'#CuOOQO'#C`'#C`O}QPO'#C_O!SQPO'#C^QOQPOOO!bQPO,59OOOQO,58{,58{OVQPO'#CoO!mQPO,59aO!xQPO,58yO#WQPO,58xOOQO'#Cf'#CfO#]QPO'#CwOOQO'#Ce'#CeO#eQPO1G.jOOQO,59Z,59ZOOQO-E6m-E6mO#jQPO'#CiOOQO'#Cl'#ClOOQO'#Cm'#CmO#rQPO'#CkOOQO'#C}'#C}O#wQPO'#C|O$PQPO1G.eO$UQPO'#CdO$ZQPO'#DTO$cQPO1G.dO$hQPO'#CnO$pQPO,59cOOQO7+$U7+$UO$xQPO,59TO%QQPO,59VO!xQPO'#CpO%VQPO,59hOOQO7+$P7+$PO#WQPO'#CqO%_QPO,59oO%gQPO7+$OOOQO,59Y,59YOOQO-E6l-E6lOOQO1G.o1G.oO!xQPO1G.qOOQO,59[,59[OOQO-E6n-E6nOOQO,59],59]OOQO-E6o-E6oOOQO<<Gj<<GjO%oQPO7+$]OOQO<<Gw<<Gw",
  stateData: "%t~OhOS~OUQOVPO~OjWOnTXoTX^TX~OVXO~OnYOoiX^iX~Oo[O~Ov]OfQXlQXuQX~OZ^O[^OmXP~OnYOoia^ia~OUQOVPOreOsfO~OVkO~OlnOmkX~OmpO~O^qOo[O~OtrO~OlsOupX~OuuO~OjWO~OvvO^wX~O^xO~OZ^O[^O~OlnOmka~OZ{O[{O~Oo|O~OlsOupa~OvvO^wa~OZ!RO[!RO~Ou!TO~O",
  goto: "$[xPPy!R!X!aPP!j!y!|PP|P|#S#S#X#_#e#kPPP#qP#wPPPP#z$QPPPPP$XQVOVh[s|XUO[s|QTOVd[s|WRO[s|RbYWRO[s|QbYQl]R!PvRaWQ_WRynVg[s|Qo_RzoQZRRcZQtiR!OtQwlR!QwXSO[s|R`WQj[R!S|Si[|R}sRm]",
  nodeNames: "⚠ Program QueryRule Query LSide Id ExclusionOp Name Func OptParams Param String Number SimpleRule Operator GroupRule And Or",
  maxTerm: 39,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "&V~RlX^!ypq!yqr#nrs#yxy$hyz$m|}$r!O!P$w!Q![$|![!]%U!^!_%Z!_!`#t!`!a%Z!c!}%c#R#S%c#T#o%c#o#p%q#p#q%v#q#r%{#r#s&Q#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#OYh~X^!ypq!y#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#qP!_!`#t~#yO^~~#|TOr#yrs$]s;'S#y;'S;=`$b<%lO#y~$bOZ~~$eP;=`<%l#y~$mOj~~$rOm~~$wOl~~$|On~~%RP[~!Q![$|~%ZOt~~%`P^~!_!`#t~%hRV~!c!}%c#R#S%c#T#o%c~%vOo~~%{Ov~~&QOu~~&VOU~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 7, get: value => spec_Name[value] || -1}],
  tokenPrec: 0
})
