// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  QueryRule = 2,
  Query = 3,
  LSide = 4,
  Id = 5,
  ExclusionOp = 6,
  Name = 7,
  Func = 8,
  OptParams = 9,
  Param = 10,
  String = 11,
  Number = 12,
  SimpleRule = 13,
  Operator = 14,
  GroupRule = 15,
  And = 16,
  Or = 17
