// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  QueryRule = 2,
  LSide = 3,
  Negation = 4,
  Identifier = 5,
  SimpleRule = 6,
  Operator = 7,
  Number = 8,
  String = 9,
  GroupRule = 10,
  And = 11,
  Or = 12
